[[redirects]]
  from = "/arc-sw.js"
  to = "https://arc.io/arc-sw.js"
  status = 200

[[redirects]]
  from = "/youtube"
  to = "https://youtube.com/RojanGamingYT"
  status = 200

[[redirects]]
  from = "/more"
  to = "https://bio.link/RojanGaming"
  status = 200

[[redirects]]
  from = "/certificates"
  to = "https://drive.google.com/drive/folders/1-DCyR6VUUtJySvAI4ppcdIe9D7BDqvB1"
  status = 200

[[redirects]]
  from = "/qrgen"
  to = "https://qr.rojansapkota.com.np/"
  status = 302

[[redirects]]
  from = "/ssgen"
  to = "https://ss.rojansapkota.com.np/"
  status = 302

[[redirects]]
  from = "/SEE"
  to = "https://see.ntc.net.np/"
  status = 200


  
