[[redirects]]
  from = "/arc-sw.js"
  to = "https://arc.io/arc-sw.js"
  status = 200

[[redirects]]
  from = "/youtube"
  to = "https://youtube.com/RojanGamingYT"
  status = 200

[[redirects]]
  from = "/more"
  to = "https://bio.link/RojanGaming"
  status = 200

[[redirects]]
  from = "/certificates"
  to = "https://drive.google.com/drive/folders/1-DCyR6VUUtJySvAI4ppcdIe9D7BDqvB1"
  status = 200



  
